### ISSUE TITLE
Test snapshot doesn't match in Windows 10

### ISSUE THREAD

**Issue by Ailrun** [kentcdodds/glamorous-website#273] opened 2017-08-22 23:02 UTC
**Problem Description:**
Snapshot has `/` in its content but as you know, Windows use `\\` to separate directory.
Therefore snapshot tests fails in Windows.

![image](https://user-images.githubusercontent.com/12473268/29591279-ccfa3950-876b-11e7-93ff-3baf311e2824.png)

**Suggested Solution:**
Sorry, I have no Idea.

**Comment by Ailrun** [comment] 2017-08-22 23:03
@kentcdodds 
Is the core problem from https://github.com/babel-utils/babel-plugin-tester ?

**Comment by kentcdodds** [comment] 2017-08-22 23:30
Ah, that's disappointing! This will need to be fixed in this project. But I'm not 100% certain how to fix it. Might be able to use `formatResult` from `babel-plugin-tester`...

Could you look into it a little bit? Change would go [here](https://github.com/kentcdodds/glamorous-website/blob/c4f74b0adb252b55dd86b82d3149392dd6e25686/other/__tests__/babel-plugin-l10-loader.js#L15) (same for the `es` and `fr` versions).

**Comment by Ailrun** [comment] 2017-08-22 23:42
@kentcdodds 
I add some fifth wheel, now-cli also can't be installed in Windows.

**Comment by kentcdodds** [comment] 2017-08-22 23:44
Weeeird...

**Comment by Ailrun** [comment] 2017-08-22 23:55
@kentcdodds 
As I understand, it takes considerable amount of time to solve because `require('babel-core').transform` doesn't support converting windows-like path to linux-like path, and to change result code manuelly, we need to parse result again, which actually babel already does.
Am I right?

**Comment by Ailrun** [comment] 2017-08-23 00:02
Ah, or maybe the problem is from https://github.com/kentcdodds/glamorous-website/blob/master/other/babel-plugin-l10n-loader.js ?

**Comment by kentcdodds** [comment] 2017-08-23 00:26
Yeah, should probably just use `path.normalize` in a few places in there...

**Comment by Ailrun** [comment] 2017-08-23 06:39
@kentcdodds 
Hm? What `path.normalize` does is normalizing a path in that OS, not normalize a path from various OS, isn't it?
I can't understand what you mean... sorry for my short understanding.

**Comment by kentcdodds** [comment] 2017-08-23 19:12
Ah, yes, you're correct, `path.normalize` doesn't do what I expected. Either way, we need to ensure that the separator is `/` rather than `\`. Would you be willing to look into doing that work (considering you are able to reproduce it).

**Comment by Ailrun** [comment] 2017-08-23 20:46
@kentcdodds Ye I will

**Comment by Ailrun** [comment] 2017-08-26 03:40
@kentcdodds The significant problem is the fact that return value of `require.resolve` acts somewhat weird.
For example, if you use `console.error` on the result of `require.resolve` directly, it returns string of relative path from the importing module. However, if you use `console.error` on modified result of `require.resolve`, it returns string of absolute path from `C:` (or any drive you have the project).

And there's no way to mimic the behavior of `require.resolve`, or at least IDK...

Do you have any idea?

**Comment by Ailrun** [comment] 2017-08-26 03:42
For more detail example,

```js
console.error(require.resolve(localPath)) // display '\\fixture\\content\\es\\index.js'
console.error(require.resolve(localPath).split(p.sep)) // display 'C:, SOMEPATHS, fixture, content, es, index.js'
```

**Comment by Ailrun** [comment] 2017-08-26 03:45
@kentcdodds Using project-relative path for fallback error message is one way to solve this, but I don't think this is good UI.

**Comment by kentcdodds** [comment] 2017-08-28 15:45
Hmmm... Why don't you open a PR and we'll see what it looks like. Thanks so much @Ailrun!

**Comment by kentcdodds** [comment] 2018-05-24 13:51
This project is now in an unmaintained status. Please see [the glamorous README](https://github.com/paypal/glamorous) for more information.

**Closed by kentcdodds** 2018-05-24 13:51 UTC
Labels: help wanted
